// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxfmnbaoxgaffdymoucu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4Zm1uYmFveGdhZmZkeW1vdWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODczNDYsImV4cCI6MjA1ODI2MzM0Nn0.Q2dE-d2SajJxIcFmtecQjjWerLOHiWTI9mqzZoYsCH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);